version: 2
machine:
  environment:
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError"'
    _JAVA_OPTIONS: "-Xms1024m -Xmx4096m"
references:
  android_config: &android_config
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-28
    resource_class: large
    environment:
      _JAVA_OPTIONS: "-Xms1024m -Xmx4096m"
      JVM_OPTS: -Xmx10248M
      TERM: dumb
jobs:
  build:
    <<: *android_config
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Assemble
          command: ./gradlew clean assembleDebug -PversionCode=${CIRCLE_BUILD_NUM}
      - store_artifacts:
          path: ~/repo/app/build/outputs/apk
          destination: apks
      - persist_to_workspace:
          root: ~/repo
          paths:
            - app/build/outputs/apk/
            - ci
  uploadHockeyApp:
    <<: *android_config
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: HockeyApp Release
          command: ./ci/hockeyapp-release.sh ~/repo/app/build/outputs/apk/debug/app-debug.apk 0


workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - uploadHockeyApp:
          requires:
            - build
